//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFProfilerTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variant
    {
        public int VariantId { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public double Price { get; set; }
        public string Quantity { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastModifyDate { get; set; }
        public Nullable<int> ProductId { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
